# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logincal.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Modifycal import Ui_Modifycal


class Ui_Logincal(object):
    def open_ModifycalWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Modifycal()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, Logincal):
        Logincal.setObjectName("Logincal")
        Logincal.resize(560, 583)
        Logincal.setStyleSheet("background-color:rgb(156, 196, 255)\n"
"")
        self.centralwidget = QtWidgets.QWidget(Logincal)
        self.centralwidget.setObjectName("centralwidget")
        self.Logintxt = QtWidgets.QLabel(self.centralwidget)
        self.Logintxt.setGeometry(QtCore.QRect(190, 30, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Logintxt.setFont(font)
        self.Logintxt.setStyleSheet("color:rgb(32, 40, 50)")
        self.Logintxt.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Logintxt.setObjectName("Logintxt")
        self.Username = QtWidgets.QLabel(self.centralwidget)
        self.Username.setGeometry(QtCore.QRect(50, 140, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Username.setFont(font)
        self.Username.setStyleSheet("color:rgb(32, 40, 50)")
        self.Username.setObjectName("Username")
        self.Password = QtWidgets.QLabel(self.centralwidget)
        self.Password.setGeometry(QtCore.QRect(50, 220, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Password.setFont(font)
        self.Password.setStyleSheet("color:rgb(32, 40, 50)")
        self.Password.setObjectName("Password")
        self.Usernameinput = QtWidgets.QLineEdit(self.centralwidget)
        self.Usernameinput.setGeometry(QtCore.QRect(200, 140, 301, 31))
        self.Usernameinput.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Usernameinput.setObjectName("Usernameinput")
        self.Passwordinput = QtWidgets.QLineEdit(self.centralwidget)
        self.Passwordinput.setGeometry(QtCore.QRect(200, 220, 301, 31))
        self.Passwordinput.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Passwordinput.setObjectName("Passwordinput")
        self.LoginButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoginButton.setGeometry(QtCore.QRect(380, 460, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LoginButton.setFont(font)
        self.LoginButton.setStyleSheet("background-color:\n"
"rgb(255, 170, 127)")
        self.LoginButton.setObjectName("LoginButton")
        self.error = QtWidgets.QLabel(self.centralwidget)
        self.error.setGeometry(QtCore.QRect(50, 340, 413, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.error.setFont(font)
        self.error.setStyleSheet("color:rgb(255, 0, 0)")
        self.error.setText("")
        self.error.setObjectName("error")
        self.ExitButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExitButton.setGeometry(QtCore.QRect(30, 460, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ExitButton.setFont(font)
        self.ExitButton.setStyleSheet("background-color:\n"
"rgb(255, 0, 0)")
        self.ExitButton.setObjectName("ExitButton")
        Logincal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Logincal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 560, 21))
        self.menubar.setObjectName("menubar")
        Logincal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Logincal)
        self.statusbar.setObjectName("statusbar")
        Logincal.setStatusBar(self.statusbar)

        self.retranslateUi(Logincal)
        QtCore.QMetaObject.connectSlotsByName(Logincal)

    def retranslateUi(self, Logincal):
        _translate = QtCore.QCoreApplication.translate
        Logincal.setWindowTitle(_translate("Logincal", "MainWindow"))
        self.Logintxt.setText(_translate("Logincal", "Login"))
        self.Username.setText(_translate("Logincal", "Username:"))
        self.Password.setText(_translate("Logincal", "Password:"))
        self.LoginButton.setText(_translate("Logincal", "Login"))
        self.ExitButton.setText(_translate("Logincal", "Exit"))
        
        self.LoginButton.clicked.connect(self.loginfunction)
        self.ExitButton.clicked.connect(Logincal.close)

    def loginfunction(self):
            username = self.Usernameinput.text()
            password = self.Passwordinput  .text()

            if len(username) == 0 or len(password) == 0:
                    self.error.setText("Please fill in all inputs")
            elif username != "sunshiro" or password != "12345678":
                    self.error.setText("Incorrect username or password")
            else:
                  self.window = QtWidgets.QMainWindow()
                  self.ui = Ui_Modifycal()
                  self.ui.setupUi(self.window)
                  self.window.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Logincal = QtWidgets.QMainWindow()
    ui = Ui_Logincal()
    ui.setupUi(Logincal)
    Logincal.show()
    sys.exit(app.exec_())
