# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Modifycal.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Modifycal(object):
    def setupUi(self, Modifycal):
        Modifycal.setObjectName("Modifycal")
        Modifycal.resize(560, 650)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        Modifycal.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Modifycal)
        self.centralwidget.setObjectName("centralwidget")
        self.Modifytheinterestrate = QtWidgets.QLabel(self.centralwidget)
        self.Modifytheinterestrate.setGeometry(QtCore.QRect(90, 20, 391, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Modifytheinterestrate.setFont(font)
        self.Modifytheinterestrate.setAlignment(QtCore.Qt.AlignCenter)
        self.Modifytheinterestrate.setObjectName("Modifytheinterestrate")
        self.rate = QtWidgets.QTextEdit(self.centralwidget)
        self.rate.setGeometry(QtCore.QRect(40, 270, 491, 251))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.rate.setFont(font)
        self.rate.setObjectName("rate")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(390, 550, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 100, 601, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 200, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        Modifycal.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Modifycal)
        self.statusbar.setObjectName("statusbar")
        Modifycal.setStatusBar(self.statusbar)

        self.retranslateUi(Modifycal)
        QtCore.QMetaObject.connectSlotsByName(Modifycal)

    def retranslateUi(self, Modifycal):
        _translate = QtCore.QCoreApplication.translate
        Modifycal.setWindowTitle(_translate("Modifycal", "MainWindow"))
        self.Modifytheinterestrate.setText(_translate("Modifycal", "Modify the interest rate"))
        self.pushButton.setText(_translate("Modifycal", "Save"))
        self.label.setText(_translate("Modifycal", "Please enter the following pattern before modify the rate number"))
        self.label_2.setText(_translate("Modifycal", "rate = __"))
        self.label_3.setText(_translate("Modifycal", "rate = __"))

        self.pushButton.clicked.connect(self.save_txt)
    
    def save_txt(self):
        with open('Rate.txt', 'w') as f:
            my_text = self.rate.toPlainText()
            f.write(my_text)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Modifycal = QtWidgets.QMainWindow()
    ui = Ui_Modifycal()
    ui.setupUi(Modifycal)
    Modifycal.show()
    sys.exit(app.exec_())
